name: Build & Push Docker Image for Pi3 + Kivy

on:
  push:
    branches: [ main ]

env:
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo owner
        run: echo "REPO_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/arm/v7
          tags: ghcr.io/${{ env.REPO_OWNER_LOWER }}/pi3-kivy:latest
